name: fitsphere
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Иконки
  cupertino_icons: ^1.0.8

  # 🔥 Firebase (все одной ветки)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # 📦 Остальные пакеты
  provider: ^6.1.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  shared_preferences: ^2.3.2

  # 📷 Фото и разрешения
  image_picker: ^1.1.1
  permission_handler: ^11.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/training_group.png
    - assets/images/lunges.png
    - assets/images/plank.png
    - assets/images/yoga.png
    - assets/icons/running_girl.png
    - assets/icons/app_icon.png
    - assets/gifs/jumping_on_the_spot.gif
    - assets/gifs/mountaineer.gif
    - assets/gifs/pull_ups.gif
    - assets/gifs/push_ups.gif
    - assets/gifs/running_on_the_spot.gif
    - assets/gifs/squats.gif
    - assets/gifs/twisting.gif
    - assets/gifs/weighted_squats.gif

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
