// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMb0G7B6n10MrV-6_21YyMG7rDBHy3aks',
    appId: '1:833447040544:web:76d11b899a9cdb58920e45',
    messagingSenderId: '833447040544',
    projectId: 'fitsphere-8be6c',
    authDomain: 'fitsphere-8be6c.firebaseapp.com',
    storageBucket: 'fitsphere-8be6c.firebasestorage.app',
    measurementId: 'G-1YDNLCFW77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodixvySSSgKbyRtSPunKjbe0A3NCuWic',
    appId: '1:833447040544:android:dd4570a2d964ecba920e45',
    messagingSenderId: '833447040544',
    projectId: 'fitsphere-8be6c',
    storageBucket: 'fitsphere-8be6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq6S2skidt0FMlWIZoO2m0A8svaXrU-pk',
    appId: '1:833447040544:ios:48fac18b4de83849920e45',
    messagingSenderId: '833447040544',
    projectId: 'fitsphere-8be6c',
    storageBucket: 'fitsphere-8be6c.firebasestorage.app',
    iosBundleId: 'com.example.fitsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq6S2skidt0FMlWIZoO2m0A8svaXrU-pk',
    appId: '1:833447040544:ios:48fac18b4de83849920e45',
    messagingSenderId: '833447040544',
    projectId: 'fitsphere-8be6c',
    storageBucket: 'fitsphere-8be6c.firebasestorage.app',
    iosBundleId: 'com.example.fitsphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMb0G7B6n10MrV-6_21YyMG7rDBHy3aks',
    appId: '1:833447040544:web:601b6e8af0438711920e45',
    messagingSenderId: '833447040544',
    projectId: 'fitsphere-8be6c',
    authDomain: 'fitsphere-8be6c.firebaseapp.com',
    storageBucket: 'fitsphere-8be6c.firebasestorage.app',
    measurementId: 'G-KGX5SKPTPP',
  );
}
